deployment:
  tasks:
    - export DEPLOYPATH=/home/n1609143/public_html/dikarizaldy.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -r images $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
