deployment:
  tasks:
    - export DEPLOYPATH=/home/n1609143/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -r img $DEPLOYPATH
    - /bin/cp -r JS $DEPLOYPATH
